XeroAPI/xero-node

- lib/application.js
The throws inside these functions were causing errors to get swallowed. Also added callback handling to the error handlers.
> Properly bubble errors up the stack

- lib/entities/shared.js
There was two LineItemSchema in shared.js, removed the one with the
incorrect Tracking Type.
> Remove arbitrary LineItemSchema from shared.js

- lib/entity_helpers/accounting/items.js
- test/accountingtests.js
Add support for multi item push using the following code:
```
var sampleItem = {
Code: 'Item-' + Math.random(),
Name: 'Fully Tracked Item',
Description: '2014 Merino Sweater',
PurchaseDescription: '2014 Merino Sweater',
PurchaseDetails: {
UnitPrice: 149.00,
AccountCode: salesAccount
},
SalesDetails: {
UnitPrice: 299.00,
AccountCode: salesAccount
}
};            
var items = [];
for (var i = 0; i < 10; i++) {
sampleItem.Code = 'Item-' + Math.random();
items.push(currentApp.core.items.newItem(sampleItem));
}
currentApp.core.items.saveItems(items)
.then(function(response) {
expect(response.entities).to.have.length.greaterThan(9);
done();
})
.catch(function(err) {
done(wrapError(err));
})
```
> Add multi item push to fix issue #39

- lib/entities/accounting/invoice.js
- lib/entities/shared.js
This attribute appeared to be missing from the schema as per [the Xero docs](https://developer.xero.com/documentation/api/invoices#LineItems). Additionally, the Url attribute in the invoice schema was mistakenly capitalised.
> Add LineItemID to LineItem schema

- docs/Attachments.md
- lib/application.js
- lib/entities/accounting/attachment.js
There was no observed way to utilise the parameter IncludeOnline when saving an attachment to an invoice, nor any way for the existing Save method to collect a value for it. As such, I've added a parameter to the save function that defaults to false (including when undefined) which should maintain API compatibility. The Xero API defaults to false for this parameter, hence the part in putOrPost only sets it if true.
> Add support for the IncludeOnline parameter in Attachment saving

- docs/Payments.md
Without double quotes around ACCRECPAYMENT getPayments returns `<Message>No property or field \'ACCRECPAYMENT\' exists in type \'Payment\'</Message>`
> Add double quotes to filter PaymentType

- lib/application.js
This fixes #69 by converting oauth responses which are url encoded to JSON and returns to the consumer.
> Fix for #69. Convert oauth errors to JSON

- lib/entities/shared.js
- test/core/contacts_tests.js
This adds test and fixes the issue around the schema for Contact addresses.
Looks like Org address works fine still. @jordanwalsh23  do you know why this still works?
Payroll has their own schemas that have the same names.
> F contactscheme

- lib/entity_helpers/accounting/banktransactions.js
- lib/entity_helpers/accounting/banktransfers.js
- lib/entity_helpers/accounting/users.js
- test/core/banktransactions_tests.js
- test/core/banktransfers_tests.js
This PR fixes the naming convention in BankTransactions and BankTransfers objects.
It also updates the 'saveAll' functions as they were not working correctly previously.
**Note: This is a breaking change so should have a minor version increment.**
> Issue 12 - Fix for BankTransactions

- README.md
- lib/application.js
- lib/oauth/oauth.js
- package.json
- test/core/receipts_tests.js
- test/mocha.opts
- test/testrunner.js
This PR fixes issue #96 adding support for the redirectOnError parameter as part of the auth flow.
> Issue 96 - Add support for 'redirectOnError' parameter during auth.

- lib/application.js
- test/core/error_tests.js
- test/core/token_tests.js
- test/testrunner.js
Adds a `statusCode` property to errors returned from authenticated API calls. This allows consumers to programatically check what the actual http error code was.
Hopefully resolves https://github.com/XeroAPI/xero-node/issues/21
Also removes a couple of unnecessary console.error() calls
> Adds 'statusCode' property to errors returned from API calls

- lib/entities/accounting/account.js
- test/core/accounts_tests.js
RE: https://github.com/XeroAPI/xero-node/issues/171
> PR#171 Preserve CurrencyCode when serializing an Accout

- lib/entities/accounting/organisation.js
Following Issue #152,
I tested this bug from version `2.11` to `2.18` which all got the same result.
Here is my [testing codes](https://github.com/XeroAPI/xero-node/files/1726416/test.txt)
Before fix:
After fix:
> Fix missing 'OrganisationID' after called organisation.toJSON()

- src/AccountingAPI-models.ts
It is needed for ACCPAY type invoices with multiple currencies.
> Add CurrencyRate to Invoice model

- src/internals/BaseAPIClient.ts
- src/internals/config-helper.ts
Setting the UserAgent to begin with an application specific value is requested as part of Xero app certification (for partner apps).
This change ensures creation of the oauthConfig object uses the userAgent configuration property (if set in the Xero config).  This will correctly set the UserAgent header for requests made to Xero API.
If a value is not provided in the config file, it will fallback to “NodeJS-XeroAPIClient” as the userAgent prefix.
The userAgent will always be suffixed with the xero-node version and the consumerKey value from the config file.
Fixes #244
> Set oauthConfig.userAgent from config

- src/AccountingAPIClient.ts
In some cases app receives file from another API, and we do not need use filesystem to store this file before uploading to xero, so we need endpoint to write file as a stream.
> Added method uploadAttachmentFromStream

- src/AccountingAPIClient.ts
When using xero-node in a Typescript project. Some methods have inconstant types and this causes valid function calls to be marked as invalid by Typescript.
E.g.
```typescript
// tsc error: ContactID is required
xero.contacts.update(body, { summarizeErrors: true });
```
> Fix 'contacts' methods parameter types

- src/AccountingAPI-models.ts
Just discovered that the `ItemCode` type is missing from the `LineItem` interface in the AccountingAPI models.
I'm not sure if this is intentional or left out by mistake. Just thought I'd create a PR anyway.
See attached Xero documentation for LineItem.
> Add missing ItemCode to LineItem model

- README.md
Documentation lacked example for get()'ing specific data entries.
Added an example where express.js is listening to a webhook for new contacts to be added in Xero so you can get the new data and then use it for something.
> Added webhook example for querying new data entries

- CHANGELOG.md
- src/xeroClient.ts
* refactor of the `buildClient()` to include the clock_tolerance custom
```
async buildClient() {
...
this.openIdClient.CLOCK_TOLERANCE = 5; // to allow a 5 second skew in the openid-client validations
}
```
* format client file 2 spaces from 2 tabs
* `fetchConnectedTenantIds` no longer private
> client refactor & issue cleanup

- src/XeroClient.ts
- src/test/xeroClient.spec.ts
It doesn't look like the state which you can pass to `IXeroClientConfig` doesn't get used anywhere so this pull request passes it to `openid-client` when calling `buildConsentUrl()`.
I've also added a test in to make sure it's working as expected, test could be made shorter by changing the original Xero object but I wasn't sure how you'd feel about it.
Let me know if I missed anything you need!
> Passed state to openid-client when building consent URL

- README.md
- src/XeroClient.ts
- src/test/mocks/connectionsResponse.json
- src/test/xeroClient.spec.ts
This PR fixes two bugs.
1) It adds a non breaking change to the `updatedTenants` function that allows you to still get the `/connections` data on the client without having to have the `accoutning.settings` scope that calls the `/organisations` endpoint for each of your active connections. #452 
A community member who had > 600 org connections discovered this to be a bug as it made 600 async calls.. The new params defaults true but if you pass `.updateTenants(false)` it won't do that call.
This was possible because the /connections endpoint now returns the `tenantName` which was not always the case.
2) Allows for configuration of max timeout of the GOT lib openid uses, and sets the default timeout to `2500 ms` #448
> Timeout Configuration

- docs/accounting/index.html
- docs/assets/index.html
- docs/bankfeeds/index.html
- docs/files/index.html
- docs/payroll-au/index.html
- docs/payroll-nz/index.html
- docs/payroll-uk/index.html
- docs/projects/index.html
- package.json
- src/gen/api/accountingApi.ts
- src/gen/api/assetApi.ts
- src/gen/api/bankfeedsApi.ts
- src/gen/api/filesApi.ts
- src/gen/api/payrollAUApi.ts
- src/gen/api/payrollNZApi.ts
- src/gen/api/payrollUKApi.ts
- src/gen/api/projectApi.ts
- src/gen/model/bankfeeds/modelError.ts
- src/gen/model/payroll-au/deductionLine.ts
- src/gen/model/payroll-uk/salaryAndWage.ts
- src/gen/model/projects/timeEntry.ts
1) fixes #484 - When a rate limit call hit 429 - the body was empty, and we were trying to JSON.parse and return the result. Now just return the body
2) Fixes #523  by Adding `summaryOnly` boolean option to getContacts
3) Few other odds and ends generated form recent OAS changes (enums, optional params, etc)
> fixing #484 json parse an empty body from a failed rate limit 429 call

- README.md
https://github.com/XeroAPI/xero-node/issues/650
> FIX-650 | Node | Syntax error in Readme
