XeroAPI/xero-node

- README.md
Could yield a better error message. Nonetheless, to lowercase seems to fix the issue. Much more testing is required.
> Updated Readme to work on default example.

- lib/entity_helpers/accounting/attachments.js
- sample_app/index.js
- sample_app/views/invoices.handlebars
> added http to https conversion on attachments

- docs/Payments.md
- lib/entities/accounting/payment.js
- lib/entity_helpers/accounting/payments.js
- package-lock.json
- test/accountingtests.js
> Change createPayment to newPayment and add multi-payment put

- package.json
- yarn.lock
> Gives xml2js a version

- lib/schemaobject/schemaobject.js
> This was causing an issue with my webpack.

- docs/Invoices.md
Using the array destructuring, our code on the docs will look more intuitive, eliminating the entities[0] portion and using proper name.
> Proposal intuitive syntax to get entities[0]

- lib/core.js
- lib/entities/accounting/repeatinginvoice.js
- lib/entity_helpers/accounting/repeatinginvoices.js
- test/core/repeatinginvoice_tests.js
- test/testrunner.js
Fix for Issue #71 which adds support for the RepeatingInvoices endpoint.
Also some linting cleanup on core.js, no functionality impacted.
> Issue 71 - Add repeating invoices

- README.md
- docs/Contact-Groups.md
- lib/core.js
- lib/entities/accounting/contactgroup.js
- lib/entity_helpers/accounting/contactgroups.js
- test/core/contactgroups_tests.js
- test/core/contacts_tests.js
- test/testrunner.js
This PR adds support for the ContactGroups endpoint including the following functions:
* Create new contact groups
* Update contact groups
* Delete contact groups
* Add contacts to groups
* Remove contacts from groups
> Issue 79 - Add support for ContactGroups

- README.md
- docs/Employees.md
- docs/README.md
- lib/core.js
- lib/entities/accounting/employee.js
- lib/entity_helpers/accounting/employees.js
- test/core/employees_tests.js
- test/testrunner.js
Fixes Issue #83.
Adds Employees SDK, including docs and tests.
> Fix for issue 83 - Add Support for Employees

- README.md
- docs/Employees.md
- docs/README.md
- docs/Receipts.md
- lib/core.js
- lib/entities/accounting/account.js
- lib/entities/accounting/employee.js
- lib/entities/accounting/manualjournal.js
- lib/entities/accounting/receipt.js
- lib/entities/accounting/repeatinginvoice.js
- lib/entities/accounting/user.js
- lib/entities/shared.js
- lib/entity_helpers/accounting/employees.js
- lib/entity_helpers/accounting/receipts.js
- lib/entity_helpers/accounting/repeatinginvoices.js
- test/core/accounts_tests.js
- test/core/attachment_tests.js
- test/core/banktransactions_tests.js
- test/core/banktransfers_tests.js
- test/core/contacts_tests.js
- test/core/creditnotes_tests.js
- test/core/employees_tests.js
- test/core/invoices_tests.js
- test/core/manualjournal_tests.js
- test/core/receipts_tests.js
- test/core/repeatinginvoice_tests.js
- test/testrunner.js
This PR adds support for the receipts endpoint and also fixes some issues in the Employees endpoint.
> Issue 87 - Add support for 'Receipts' Endpoint

- README.md
- docs/Overpayments.md
- docs/README.md
- lib/core.js
- lib/entities/accounting/allocation.js
- lib/entities/accounting/creditnote.js
- lib/entities/accounting/overpayment.js
- lib/entities/shared.js
- lib/entity_helpers/accounting/allocations.js
- lib/entity_helpers/accounting/overpayments.js
- test/core/overpayments_tests.js
- test/testrunner.js
This PR adds a fix for Issue #99 adding support for the overpayments endpoint.
> Issue 99 - Add support for Overpayments

- README.md
- docs/Overpayments.md
- docs/Prepayments.md
- docs/README.md
- docs/Repeating-Invoices.md
- lib/core.js
- lib/entities/accounting/allocation.js
- lib/entities/accounting/creditnote.js
- lib/entities/accounting/overpayment.js
- lib/entities/accounting/prepayment.js
- lib/entities/shared.js
- lib/entity_helpers/accounting/allocations.js
- lib/entity_helpers/accounting/overpayments.js
- lib/entity_helpers/accounting/prepayments.js
- test/core/attachment_tests.js
- test/core/banktransactions_tests.js
- test/core/overpayments_tests.js
- test/core/prepayments_tests.js
- test/testrunner.js
Also fixes documentation issue for repeatinginvoices and a minor bug in attachments tests where purchaseorder attachments weren't being tested correctly.
> Issue 100 - Add support for prepayments endpoint

- README.md
- docs/Linked-Transactions.md
- docs/Overpayments.md
- docs/Prepayments.md
- docs/README.md
- docs/Repeating-Invoices.md
- lib/core.js
- lib/entities/accounting/allocation.js
- lib/entities/accounting/creditnote.js
- lib/entities/accounting/linkedtransaction.js
- lib/entities/accounting/overpayment.js
- lib/entities/accounting/prepayment.js
- lib/entities/shared.js
- lib/entity_helpers/accounting/allocations.js
- lib/entity_helpers/accounting/linkedtransactions.js
- lib/entity_helpers/accounting/overpayments.js
- lib/entity_helpers/accounting/prepayments.js
- test/core/attachment_tests.js
- test/core/banktransactions_tests.js
- test/core/expenseclaims_tests.js
- test/core/linkedtransactions_tests.js
- test/core/overpayments_tests.js
- test/core/prepayments_tests.js
- test/core/receipts_tests.js
- test/testrunner.js
Adds support for the linked transactions endpoint (fix for #101 )
This PR adds the last endpoint in the accounting api and should be sufficient to move this SDK to a BETA status.
> Issue 101 - Add support for linked transactions

- lib/entities/accounting/taxrate.js
- test/core/taxrate_tests.js
Add support for non-recoverable tax components that have recently been added to the API: https://developer.xero.com/documentation/api/tax-rates
> Add IsNonRecoverable property to TaxComponent

- lib/entities/accounting/manualjournal.js
Added Options to saving Manual Journals and using ManualJournalID instead of JournalID in save
> Options on Manual Journals and using ManualJournalID

- lib/entity_helpers/payroll/employees.js
removed the entityName argument from the EntityHelper.call
> Fixed bug in Payroll Employee Entity

- lib/application.js
- lib/entity_helpers/accounting/invoices.js
I had an issue where line totals didn't match when trying to update an invoice, if it had 4 decimal places
> Added unitdp to GetInvoice

- lib/application.js
Fixed references to the `data` variable, which is not in scope in a few places.
> Fix error references

- lib/entities/shared.js
see https://github.com/XeroAPI/xero-node/pull/43#issuecomment-361434521
> add LineItemID back to LineItemSchema

- src/AccountingAPIClient.ts
- src/__tests__/AccountingAPI-endpoint.tests.ts
Enable getting creditNotes by CreditNoteNumber much like you can get invoices by InvoiceNumber
> Enable getting creditNotes by CreditNoteNumber

- README.md
Fixed some typos in the README
> [fix] Fix typos

- src/AccountingAPI-models.ts
- src/__integration_tests__/request-body/invoice.request.examples.ts
I think it would be nice to have `Url` so that it can reference back to its source.
What else needs to be done?
> add Url attribute to Invoice model

- src/AccountingAPIClient.ts
Prevents linting errors.
Fixes #223
> add optional args to reports get

- src/AccountingAPI-models.ts
> Add ContactNumber to Contact model

- src/ProjectsAPIClient.ts
- src/index.ts
This builds on #221 and includes the ability to create a project through the beta api
> add post call to projects endpoint

- src/AccountingAPI-models.ts
- src/AccountingAPI-responses.ts
- src/AccountingAPIClient.ts
- src/__tests__/AccountingAPI-endpoint.tests.ts
- src/internals/__tests__/utils.tests.ts
recreated from #234, courtesy of @corymsmith
> Add paymentservices

- src/AccountingAPI-models.ts
- src/AccountingAPI-responses.ts
- src/AccountingAPIClient.ts
- src/__tests__/AccountingAPI-endpoint.tests.ts
This addresses #233 
This is a work in progress so I'm creating this for visibility as I don't have the proper partner access yet to run integration tests.
> WIP: Adding PaymentServices support

- src/AccountingAPIClient.ts
- src/__tests__/AccountingAPI-history.tests.ts
recreated from #277 with credit to @NickLewry
> add support to create a History note on all supported endpoints

- src/xeroClient.ts
correctly applies client's clock skew tolerance.
> fix: correctly apply clock tolerance

- .gitignore
- .npmignore
- CHANGELOG.md
- package.json
- src/gen/api/accountingApi.ts
- src/gen/model/accounting/models.ts
- src/gen/model/accounting/payment.ts
- tsconfig.json
* Adds OAuth 2 Gateway to fix #https://github.com/XeroAPI/xero-node/issues/328
* Adds Fix for serializer for the numerous dates returned by XeroAPI to fix #https://github.com/XeroAPI/xero-node/issues/323
Possible raw date formats
`"Date": "2009-03-29",`
`"DateString": "2016-12-16T00:00:00",`
`"DateUTCString": "2018-02-28T21:02:11",`
`"createdDateUtc": "2020-01-08T17:26:30.5778680",`
MS Format ( this was main problem date )
`"FullyPaidOnDate": "\/Date(1481846400000+0000)\/",`
ref: https://developer.xero.com/documentation/api/requests-and-responses
> quotes and date fix

- CHANGELOG.md
- package.json
- src/gen/api/accountingApi.ts
- src/gen/model/accounting/account.ts
- src/gen/model/accounting/invoice.ts
- src/gen/model/accounting/models.ts
- src/gen/model/accounting/quote.ts
The serialize function was used a lot more than I thought - meta programming 🤕  #human #learnings
> Serializer bug fix

- CHANGELOG.md
- package.json
- src/XeroClient.ts
just wanted to double check this is all that's involved for XeroClient.ts changes
> changes to update tenant function in XeroClient

- README.md
- package.json
- src/XeroClient.ts
- src/test/xeroClient.spec.ts
Including in next release readme docs for how to access state + beef up some tests.
> Readme update for state

- README.md
- docs/v4/files/index.html
* Update the docs to include the files API additions.
* Add docs to the Readme
> Files docs

- docs/accounting/index.html
- docs/assets/index.html
- docs/bankfeeds/index.html
- docs/files/index.html
- docs/payroll-au/index.html
- docs/payroll-nz/index.html
- docs/payroll-uk/index.html
- docs/projects/index.html
The javascript to route redirect needs a safe link `#`
> fix broken link in docs

- README.md
Fixed link to sso example & added the SSU example
> Updated Sample Apps

- README.md
- src/XeroClient.ts
- src/test/xeroClient.spec.ts
For #614 
I also added clock tolerance while I was there, In my WSL env my system clock can get skewed upto 10 seconds or so. So the option to slacken this in dev would be awesome.
> Add timeout, and clock tolerance configuration options

- .github/workflows/test.yml
- docs/accounting/index.html
- docs/appstore/index.html
- docs/assets/index.html
- docs/bankfeeds/index.html
- docs/files/index.html
- docs/finance/index.html
- docs/payroll-au/index.html
- docs/payroll-nz/index.html
- docs/payroll-uk/index.html
- docs/projects/index.html
- jest.config.js
- package-lock.json
- package.json
- src/XeroClient.ts
- src/gen/api/accountingApi.ts
- src/gen/api/appStoreApi.ts
- src/gen/api/assetApi.ts
- src/gen/api/bankfeedsApi.ts
- src/gen/api/filesApi.ts
- src/gen/api/financeApi.ts
- src/gen/api/payrollAUApi.ts
- src/gen/api/payrollNZApi.ts
- src/gen/api/payrollUKApi.ts
- src/gen/api/projectApi.ts
issue - https://github.com/XeroAPI/xero-node/issues/639
> #639 | fixes npm audit issues

- package-lock.json
- package.json
- src/XeroClient.ts
https://github.com/XeroAPI/xero-node/issues/636
https://github.com/XeroAPI/xero-node/issues/684
> Fix 636 | Open ID Upgrade

- docs/accounting/index.html
- docs/appstore/index.html
- docs/assets/index.html
- docs/bankfeeds/index.html
- docs/files/index.html
- docs/finance/index.html
- docs/payroll-au/index.html
- docs/payroll-nz/index.html
- docs/payroll-uk/index.html
- docs/projects/index.html
- package.json
- src/gen/api/accountingApi.ts
- src/gen/api/appStoreApi.ts
- src/gen/api/assetApi.ts
- src/gen/api/bankfeedsApi.ts
- src/gen/api/filesApi.ts
- src/gen/api/financeApi.ts
- src/gen/api/payrollAUApi.ts
- src/gen/api/payrollNZApi.ts
- src/gen/api/payrollUKApi.ts
- src/gen/api/projectApi.ts
- https://xero.atlassian.net/browse/PETOSS-402
- https://xero.atlassian.net/browse/PETOSS-440
> Fix 679 | 686 | Upload attachment issue
